#!/bin/tcsh -f
echo "Testing Complex"

/bin/rm -rf Created/Complex

foreach f (  Tests/Complex/*.x )
	set F = ${f:t:r}

	echo "./BuildTemp/Linux/Debug/bin/protocolgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Complex/xdr/${F}_xdr.cpp --lang=CPP -DRPC_HDR -DXDR_HDR --xdr"
	./BuildTemp/Linux/Debug/bin/protocolgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Complex/xdr/${F}_xdr.cpp --lang=CPP -DRPC_HDR -DXDR_HDR --xdr
	
	echo "./BuildTemp/Linux/Debug/bin/protocolgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Complex/headers/${F}.hpp --lang=CPP -DRPC_HDR -DXDR_HDR --headers"
	./BuildTemp/Linux/Debug/bin/protocolgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Complex/headers/${F}.hpp --lang=CPP -DRPC_HDR -DXDR_HDR --headers
		
	echo "./BuildTemp/Linux/Debug/bin/protocolgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Complex/abnf/${F}.abnf --lang=CPP -DRPC_HDR -DXDR_HDR --abnf"
	./BuildTemp/Linux/Debug/bin/protocolgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Complex/abnf/${F}.abnf --lang=CPP -DRPC_HDR -DXDR_HDR --abnf

	echo "./BuildTemp/Linux/Debug/bin/protocolgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Complex/stubs/${F}.cpp --lang=CPP -DRPC_HDR -DXDR_HDR --stubs"
	./BuildTemp/Linux/Debug/bin/protocolgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/stubs/Complex/${F}.cpp --lang=CPP -DRPC_HDR -DXDR_HDR --stubs

	echo "./BuildTemp/Linux/Debug/bin/protocolgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Complex/server/${F}.cpp --lang=CPP -DRPC_HDR -DXDR_HDR --server"
	./BuildTemp/Linux/Debug/bin/protocolgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Complex/server/${F}.cpp --lang=CPP -DRPC_HDR -DXDR_HDR --server
end

