#!/bin/tcsh -f
echo "Testing Version"

/bin/rm -rf Created/Version

foreach f (  Tests/Version/*.x )
	set F = ${f:t:r}

	echo "./BuildTemp/Linux/Debug/bin/protocolgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Version/xdr/${F}_xdr.cpp --lang=CPP -DRPC_HDR -DXDR_HDR --xdr"
	./BuildTemp/Linux/Debug/bin/protocolgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Version/xdr/${F}_xdr.cpp --lang=CPP -DRPC_HDR -DXDR_HDR --xdr
	
	echo "./BuildTemp/Linux/Debug/bin/protocolgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Version/headers/${F}.hpp --lang=CPP -DRPC_HDR -DXDR_HDR --headers"
	./BuildTemp/Linux/Debug/bin/protocolgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Version/headers/${F}.hpp --lang=CPP -DRPC_HDR -DXDR_HDR --headers
		
	echo "./BuildTemp/Linux/Debug/bin/protocolgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Version/abnf/${F}.abnf --lang=CPP -DRPC_HDR -DXDR_HDR --abnf"
	./BuildTemp/Linux/Debug/bin/protocolgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Version/abnf/${F}.abnf --lang=CPP -DRPC_HDR -DXDR_HDR --abnf

	echo "./BuildTemp/Linux/Debug/bin/protocolgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Version/stubs/${F}.cpp --lang=CPP -DRPC_HDR -DXDR_HDR --stubs"
	./BuildTemp/Linux/Debug/bin/protocolgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Version/stubs/${F}.cpp --lang=CPP -DRPC_HDR -DXDR_HDR --stubs

	echo "./BuildTemp/Linux/Debug/bin/protocolgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Version/server/${F}.cpp --lang=CPP -DRPC_HDR -DXDR_HDR --server"
	./BuildTemp/Linux/Debug/bin/protocolgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Version/server/${F}.cpp --lang=CPP -DRPC_HDR -DXDR_HDR --server
end

