#!/bin/tcsh -f
echo "Testing Const"

/bin/rm -rf Created/Const

foreach f (  Tests/Const/*.x )
	set F = ${f:t:r}

	echo "./BuildTemp/Linux/Debug/bin/xdrgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Const/xdr/${F}_xdr.cpp --lang=CPP -DRPC_HDR -DXDR_HDR --xdr"
	./BuildTemp/Linux/Debug/bin/xdrgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Const/xdr/${F}_xdr.c --lang=CPP -DRPC_HDR -DXDR_HDR --xdr
	
	echo "./BuildTemp/Linux/Debug/bin/xdrgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Const/headers/${F}.hpp --lang=CPP -DRPC_HDR -DXDR_HDR --headers"
	./BuildTemp/Linux/Debug/bin/xdrgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Const/headers/${F}.hpp --lang=CPP -DRPC_HDR -DXDR_HDR --headers
		
	echo "./BuildTemp/Linux/Debug/bin/xdrgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Const/abnf/${F}.cpp --lang=CPP -DRPC_HDR -DXDR_HDR --abnf"
	./BuildTemp/Linux/Debug/bin/xdrgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Const/abnf/${F}.cpp --lang=CPP -DRPC_HDR -DXDR_HDR --abnf

	echo "./BuildTemp/Linux/Debug/bin/xdrgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Const/stubs/${F}.cpp --lang=CPP -DRPC_HDR -DXDR_HDR --stubs"
	./BuildTemp/Linux/Debug/bin/xdrgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/stubs/Const/${F}.cpp --lang=CPP -DRPC_HDR -DXDR_HDR --stubs

	echo "./BuildTemp/Linux/Debug/bin/xdrgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Const/server/${F}.cpp --lang=CPP -DRPC_HDR -DXDR_HDR --server"
	./BuildTemp/Linux/Debug/bin/xdrgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Const/server/${F}.cpp --lang=CPP -DRPC_HDR -DXDR_HDR --server
end

