#!/bin/tcsh -f
echo "Testing Method"

/bin/rm -rf Created/Method

foreach f (  Tests/Method/*.x )
	set F = ${f:t:r}

	echo "./BuildTemp/Linux/Debug/bin/xdrgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Method/xdr/${F}_xdr.cpp --lang=CPP -DRPC_HDR -DXDR_HDR --xdr"
	./BuildTemp/Linux/Debug/bin/xdrgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Method/xdr/${F}_xdr.cpp --lang=CPP -DRPC_HDR -DXDR_HDR --xdr
	
	echo "./BuildTemp/Linux/Debug/bin/xdrgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Method/headers/${F}.hpp --lang=CPP -DRPC_HDR -DXDR_HDR --headers"
	./BuildTemp/Linux/Debug/bin/xdrgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Method/headers/${F}.hpp --lang=CPP -DRPC_HDR -DXDR_HDR --headers
		
	echo "./BuildTemp/Linux/Debug/bin/xdrgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Method/abnf/${F}.abnf --lang=CPP -DRPC_HDR -DXDR_HDR --abnf"
	./BuildTemp/Linux/Debug/bin/xdrgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Method/abnf/${F}.abnf --lang=CPP -DRPC_HDR -DXDR_HDR --abnf

	echo "./BuildTemp/Linux/Debug/bin/xdrgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Method/stubs/${F}.cpp --lang=CPP -DRPC_HDR -DXDR_HDR --stubs"
	./BuildTemp/Linux/Debug/bin/xdrgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Method/Method/${F}.cpp --lang=CPP -DRPC_HDR -DXDR_HDR --stubs

	echo "./BuildTemp/Linux/Debug/bin/xdrgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Method/server/${F}.cpp --lang=CPP -DRPC_HDR -DXDR_HDR --server"
	./BuildTemp/Linux/Debug/bin/xdrgen --namespace=RiverExplorer:Phoenix --input $f --out=Created/Method/server/${F}.cpp --lang=CPP -DRPC_HDR -DXDR_HDR --server
end

